#Set this to false if you don't want players to get teleported on clicking the shopkeeper in the gui.
AllowTeleportToShopkeepers: true

#Enable this if bedrock players play in you server(Geyser plugin)
#Note: you need to have a prefix before the bedrock player's name for this to work(you need to have FloodGate Installed to change bedrock prefix).
Geyser-Compat:
  Enabled: false
  Name-Prefix: 'B_'